### ISSUE TITLE
Commands handling?

### ISSUE THREAD

**Issue by joegalaxy71** [Syfaro/telegram-bot-api#28]
That would be very interesting. There are various cases, like if you message a bot in a group and send him "/command@bot".

**Comment by Syfaro** [comment]
The goal of this library is just to provide support for interfacing with Telegram, not handle typical bot related functions for you. 

At some point I may create a second library for handling commands and the like, but that is outside the scope of this project.

**Comment by Syfaro** [comment]
I've started a new project for this, https://github.com/Syfaro/finch

**Comment by fabioxgn** [comment]
@Syfaro I have a project that might do what you want, please take a look at: https://github.com/go-chat-bot/bot

I don't use telegram, so I just implemented basic support for it using this project.

But maybe it will save you some time using my project instead of using your own, as it already have some plugins: https://github.com/go-chat-bot/plugins

**Comment by Syfaro** [comment]
Huh, that's really neat :)
